/* Generated by GOB (v2.0.9) on Tue May 10 14:56:13 2005
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 9

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "feedmerge-feed.h"

#include "feedmerge-feed-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) FEEDMERGE_FEED(x)
#define SELF_CONST(x) FEEDMERGE_FEED_CONST(x)
#define IS_SELF(x) FEEDMERGE_IS_FEED(x)
#define TYPE_SELF FEEDMERGE_TYPE_FEED
#define SELF_CLASS(x) FEEDMERGE_FEED_CLASS(x)

#define SELF_GET_CLASS(x) FEEDMERGE_FEED_GET_CLASS(x)

/* self typedefs */
typedef FeedMergeFeed Self;
typedef FeedMergeFeedClass SelfClass;

/* here are local prototypes */
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void feedmerge_feed_init (FeedMergeFeed * o) G_GNUC_UNUSED;
static void feedmerge_feed_class_init (FeedMergeFeedClass * c) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_URI
};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_dump feedmerge_feed_dump
#define self_add_item feedmerge_feed_add_item
#define self_new feedmerge_feed_new
GType
feedmerge_feed_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (FeedMergeFeedClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) feedmerge_feed_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (FeedMergeFeed),
			0 /* n_preallocs */,
			(GInstanceInitFunc) feedmerge_feed_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "FeedMergeFeed", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((FeedMergeFeed *)g_object_new(feedmerge_feed_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static FeedMergeFeed * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static FeedMergeFeed *
GET_NEW_VARG (const char *first, ...)
{
	FeedMergeFeed *ret;
	va_list ap;
	va_start (ap, first);
	ret = (FeedMergeFeed *)g_object_new_valist (feedmerge_feed_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "FeedMerge:Feed::finalize"
	FeedMergeFeed *self  G_GNUC_UNUSED = FEEDMERGE_FEED (obj_self);
	gpointer priv = self->_priv;
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#define items (self->_priv->items)
#define VAR items
	{
#line 13 "feedmerge-feed.gob"
	
                        g_slist_foreach(VAR, (GFunc) g_object_unref, NULL);
                        g_slist_free(VAR);
                }
#line 115 "feedmerge-feed.c"
	memset(&items, 0, sizeof(items));
#undef VAR
#undef items
#line 19 "feedmerge-feed.gob"
	if(self->_priv->doc) { ((*(void (*)(void *))xmlFreeDoc)) (self->_priv->doc); self->_priv->doc = NULL; }
#line 121 "feedmerge-feed.c"
#line 22 "feedmerge-feed.gob"
	if(self->_priv->uri) { ((*(void (*)(void *))g_free)) (self->_priv->uri); self->_priv->uri = NULL; }
#line 124 "feedmerge-feed.c"
	g_free (priv);
}
#undef __GOB_FUNCTION__

static void 
feedmerge_feed_init (FeedMergeFeed * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "FeedMerge:Feed::init"
	o->_priv = g_new0 (FeedMergeFeedPrivate, 1);
}
#undef __GOB_FUNCTION__
static void 
feedmerge_feed_class_init (FeedMergeFeedClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "FeedMerge:Feed::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string
		("uri" /* name */,
		 _("Uri") /* nick */,
		 _("Uri of the feed") /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE));
	g_object_class_install_property (g_object_class,
		PROP_URI,
		param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "FeedMerge:Feed::get_property"
{
	FeedMergeFeed *self G_GNUC_UNUSED;

	self = FEEDMERGE_FEED (object);

	switch (property_id) {
	case PROP_URI:
		{
#line 26 "feedmerge-feed.gob"

                        g_value_set_string(VAL, self->_priv->uri);
                
#line 180 "feedmerge-feed.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 30 "feedmerge-feed.gob"
void 
feedmerge_feed_dump (FeedMergeFeed * self)
#line 200 "feedmerge-feed.c"
{
#define __GOB_FUNCTION__ "FeedMerge:Feed::dump"
#line 30 "feedmerge-feed.gob"
	g_return_if_fail (self != NULL);
#line 30 "feedmerge-feed.gob"
	g_return_if_fail (FEEDMERGE_IS_FEED (self));
#line 207 "feedmerge-feed.c"
{
#line 30 "feedmerge-feed.gob"
	
                g_slist_foreach(self->_priv->items, (GFunc) feedmerge_feed_item_dump, NULL);
        }}
#line 213 "feedmerge-feed.c"
#undef __GOB_FUNCTION__

#line 34 "feedmerge-feed.gob"
void 
feedmerge_feed_add_item (FeedMergeFeed * self, FeedMergeFeedItem * i)
#line 219 "feedmerge-feed.c"
{
#define __GOB_FUNCTION__ "FeedMerge:Feed::add_item"
#line 34 "feedmerge-feed.gob"
	g_return_if_fail (self != NULL);
#line 34 "feedmerge-feed.gob"
	g_return_if_fail (FEEDMERGE_IS_FEED (self));
#line 34 "feedmerge-feed.gob"
	g_return_if_fail (i != NULL);
#line 34 "feedmerge-feed.gob"
	g_return_if_fail (FEEDMERGE_IS_FEED_ITEM (i));
#line 230 "feedmerge-feed.c"
{
#line 34 "feedmerge-feed.gob"
	
                self->_priv->items = g_slist_append(self->_priv->items, i);
        }}
#line 236 "feedmerge-feed.c"
#undef __GOB_FUNCTION__

#line 38 "feedmerge-feed.gob"
GObject * 
feedmerge_feed_new (void)
#line 242 "feedmerge-feed.c"
{
#define __GOB_FUNCTION__ "FeedMerge:Feed::new"
{
#line 38 "feedmerge-feed.gob"
	
                GObject *ret;

                ret = GET_NEW;
                return ret;
        }}
#line 253 "feedmerge-feed.c"
#undef __GOB_FUNCTION__
